default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: job_applications_development

test:
  <<: *default
  database: job_applications_test

production:
  primary:
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    url: <%= ENV['DATABASE_URL'] %>
